// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/arcade/workspace/workflow-improvement/main-service/events/kafka_producer.go
//
// Generated by this command:
//
//	mockgen -destination /Users/arcade/workspace/workflow-improvement/main-service/mocks/events/mocks.go -package events_mocks -source /Users/arcade/workspace/workflow-improvement/main-service/events/events.go -source /Users/arcade/workspace/workflow-improvement/main-service/events/kafka_producer.go
//

// Package events_mocks is a generated GoMock package.
package events_mocks
