// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/arcade/workspace/workflow-improvement/main-service/cache/redis.go
//
// Generated by this command:
//
//	mockgen -destination /Users/arcade/workspace/workflow-improvement/main-service/mocks/cache/mocks.go -package cache_mocks -source /Users/arcade/workspace/workflow-improvement/main-service/cache/cache.go -source /Users/arcade/workspace/workflow-improvement/main-service/cache/redis.go
//

// Package cache_mocks is a generated GoMock package.
package cache_mocks
