// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/arcade/workspace/workflow-improvement/main-service/handlers/items.go
//
// Generated by this command:
//
//	mockgen -destination /Users/arcade/workspace/workflow-improvement/main-service/mocks/handlers/mocks.go -package handlers_mocks -source /Users/arcade/workspace/workflow-improvement/main-service/handlers/items.go
//

// Package handlers_mocks is a generated GoMock package.
package handlers_mocks
